export type CreatorProfile = {
  id: number;
  name: string;
  handle: string;
  avatar: string;
  avatarUrl: string;
  niche: string;
  platforms: string[];
  followers: string;
  engagement: string;
  matchScore: number;
  style: string;
  collab: string;
  mutual: number;
  verified: boolean;
  color: string;
};

export const CREATORS_BY_PERSONA: Record<string, { niches: string[]; creators: CreatorProfile[] }> = {
  // 1. ARIA THORNE — Fitness & Cyber-Aesthetics
  instagram: {
    niches: ["All", "Bio-Hacking", "Athleisure & 3D Gear", "High-Flow Mobility", "Sensory Gastronomy", "Cinematic Motion"],
    creators: [
      {
        id: 101,
        name: "Elena Rostova",
        handle: "@elena.vfx",
        avatar: "ER",
        avatarUrl: "/avatars/elena.jpg",
        niche: "Cinematic Motion & 3D Visuals",
        platforms: ["instagram", "tiktok"],
        followers: "420K",
        engagement: "9.4%",
        matchScore: 98,
        style: "Cyberpunk workout renders, neon telemetry overlays & kinetic pacing",
        collab: "3D fitness intro visualizer, cybernetic muscle fiber drop reels",
        mutual: 7,
        verified: true,
        color: "from-pink-500 via-purple-600 to-cyan-400",
      },
      {
        id: 102,
        name: "Zara Chen",
        handle: "@zarastyle.lab",
        avatar: "ZC",
        avatarUrl: "/avatars/zara.jpg",
        niche: "Athleisure & 3D Gear",
        platforms: ["instagram", "tiktok"],
        followers: "530K",
        engagement: "10.3%",
        matchScore: 97,
        style: "Futuristic compression suits, thermal imaging aesthetics & workout lookbooks",
        collab: "Cyber-athletic capsule drops, high-voltage sprint transitions",
        mutual: 6,
        verified: true,
        color: "from-rose-500 via-pink-600 to-purple-600",
      },
      {
        id: 103,
        name: "Dr. Maya Lindqvist",
        handle: "@mayabrain.neuro",
        avatar: "ML",
        avatarUrl: "/avatars/maya.jpg",
        niche: "High-Flow Mobility",
        platforms: ["instagram", "youtube"],
        followers: "310K",
        engagement: "8.8%",
        matchScore: 95,
        style: "Neuromuscular speed reflexes, breathwork telemetry & cold exposure breakdowns",
        collab: "Dopamine-reset workout challenges, VO2 max endurance masterclasses",
        mutual: 5,
        verified: true,
        color: "from-teal-400 via-cyan-500 to-blue-600",
      },
      {
        id: 104,
        name: "Kenji Takahashi",
        handle: "@kenji_beats",
        avatar: "KT",
        avatarUrl: "/avatars/kenji.jpg",
        niche: "Bio-Hacking",
        platforms: ["instagram", "tiktok"],
        followers: "680K",
        engagement: "12.1%",
        matchScore: 94,
        style: "140 BPM workout motivation beats, industrial modular bass & spatial pacing",
        collab: "Original high-rep workout audio tracks, viral HIIT cadence drops",
        mutual: 4,
        verified: true,
        color: "from-cyan-400 via-blue-500 to-indigo-600",
      },
      {
        id: 105,
        name: "Tariq Al-Mansoor",
        handle: "@tariqculinary",
        avatar: "TM",
        avatarUrl: "/avatars/tariq.jpg",
        niche: "Sensory Gastronomy",
        platforms: ["instagram", "youtube"],
        followers: "460K",
        engagement: "8.2%",
        matchScore: 92,
        style: "Anabolic culinary art, macroscopic protein prep & gourmet macro fuel",
        collab: "Elite athlete meal prep reels, gourmet 200g protein masterclass",
        mutual: 4,
        verified: true,
        color: "from-yellow-500 via-amber-500 to-red-500",
      },
      {
        id: 106,
        name: "Mateo Silva",
        handle: "@mateocode",
        avatar: "MS",
        avatarUrl: "/avatars/mateo.jpg",
        niche: "Bio-Hacking",
        platforms: ["instagram", "youtube"],
        followers: "285K",
        engagement: "7.9%",
        matchScore: 90,
        style: "Real-time heart rate shader visualizers, wearable sensor data overlays",
        collab: "Live HRV biometric co-streams, workout telemetry filter lenses",
        mutual: 3,
        verified: true,
        color: "from-emerald-400 via-teal-500 to-cyan-600",
      },
      {
        id: 107,
        name: "Amara Diop",
        handle: "@amarastories",
        avatar: "AD",
        avatarUrl: "/avatars/amara.jpg",
        niche: "Cinematic Motion & 3D Visuals",
        platforms: ["instagram", "youtube"],
        followers: "195K",
        engagement: "9.1%",
        matchScore: 89,
        style: "Golden hour track cinematography, explosive visual rhythm & spoken grit",
        collab: "Mini-documentary: 'The 5 AM Iron Mind', aesthetic workout shorts",
        mutual: 3,
        verified: true,
        color: "from-amber-400 via-orange-500 to-rose-600",
      },
      {
        id: 108,
        name: "Liam O'Connor",
        handle: "@liamocreator",
        avatar: "LO",
        avatarUrl: "/avatars/liam.jpg",
        niche: "Athleisure & 3D Gear",
        platforms: ["instagram", "youtube"],
        followers: "140K",
        engagement: "8.6%",
        matchScore: 87,
        style: "Fitness creator brand breakdowns, sponsor teardowns & gym gear tours",
        collab: "Sponsorship strategy for fitness creators roundtable",
        mutual: 2,
        verified: false,
        color: "from-indigo-500 via-purple-600 to-pink-500",
      },
      {
        id: 109,
        name: "Soren Kjaer",
        handle: "@soren_calisthenics",
        avatar: "SK",
        avatarUrl: "/avatars/kai.jpg",
        niche: "High-Flow Mobility",
        platforms: ["instagram", "tiktok"],
        followers: "390K",
        engagement: "11.4%",
        matchScore: 86,
        style: "Zero-gravity bodyweight acrobatics, brutal bar flows & mobility secrets",
        collab: "Gymnast vs Bodybuilder strength challenge, bar skill exchange",
        mutual: 4,
        verified: true,
        color: "from-cyan-400 via-blue-500 to-purple-600",
      },
      {
        id: 110,
        name: "Chloe Vane",
        handle: "@chloevane.pilates",
        avatar: "CV",
        avatarUrl: "/avatars/nova.jpg",
        niche: "High-Flow Mobility",
        platforms: ["instagram", "tiktok"],
        followers: "510K",
        engagement: "9.8%",
        matchScore: 85,
        style: "Ultra-precise reformer mechanics, aesthetic posture arcs & deep core work",
        collab: "Heavy lifting vs Reformer cross-training experiment",
        mutual: 3,
        verified: true,
        color: "from-purple-500 via-pink-500 to-rose-400",
      },
      {
        id: 111,
        name: "Dante Rossi",
        handle: "@dante_strength",
        avatar: "DR",
        avatarUrl: "/avatars/marcus.jpg",
        niche: "Bio-Hacking",
        platforms: ["instagram", "youtube"],
        followers: "220K",
        engagement: "8.4%",
        matchScore: 83,
        style: "Powerlifting biomechanics, eccentric overload physics & tendon armor",
        collab: "Brutal deadlift form overhaul, PR diagnostic session",
        mutual: 1,
        verified: false,
        color: "from-orange-500 via-red-500 to-purple-600",
      },
      {
        id: 112,
        name: "Mei Lin",
        handle: "@meilin_kinetic",
        avatar: "ML",
        avatarUrl: "/avatars/elena.jpg",
        niche: "Athleisure & 3D Gear",
        platforms: ["instagram", "tiktok"],
        followers: "340K",
        engagement: "10.8%",
        matchScore: 82,
        style: "Neon-lit night runs, tactical sports bras, waterproof sneaker teardowns",
        collab: "Midnight sprint challenge & wearable gear stress test",
        mutual: 2,
        verified: true,
        color: "from-emerald-400 via-cyan-500 to-blue-500",
      },
      {
        id: 113,
        name: "Jaxson Cole",
        handle: "@jaxson_iron",
        avatar: "JC",
        avatarUrl: "/avatars/mateo.jpg",
        niche: "Bio-Hacking",
        platforms: ["instagram", "tiktok"],
        followers: "440K",
        engagement: "9.2%",
        matchScore: 80,
        style: "Hypertrophy science, muscle biopsy breakdowns & micro-periodization",
        collab: "Optimal rep tempo comparison, 4-week delt expansion test",
        mutual: 2,
        verified: true,
        color: "from-blue-500 via-indigo-500 to-pink-500",
      },
      {
        id: 114,
        name: "Nia Okonjo",
        handle: "@nia_endurance",
        avatar: "NO",
        avatarUrl: "/avatars/amara.jpg",
        niche: "High-Flow Mobility",
        platforms: ["instagram", "youtube"],
        followers: "175K",
        engagement: "8.9%",
        matchScore: 78,
        style: "Ultra-marathon fueling, electrolyte balance & mental grit monologues",
        collab: "Lift & Run hybrid athlete split: 7-day documentation",
        mutual: 1,
        verified: false,
        color: "from-amber-400 via-pink-500 to-rose-500",
      },
      {
        id: 115,
        name: "Rocco DeLuca",
        handle: "@rocco_fuel",
        avatar: "RD",
        avatarUrl: "/avatars/tariq.jpg",
        niche: "Sensory Gastronomy",
        platforms: ["instagram", "tiktok"],
        followers: "310K",
        engagement: "7.7%",
        matchScore: 76,
        style: "Single-skillet 10-minute protein bowls, quick macro hacks for lifters",
        collab: "3 High-protein sweet tooth hacks under 350 calories",
        mutual: 0,
        verified: false,
        color: "from-yellow-400 via-orange-500 to-amber-600",
      },
    ],
  },

  // 2. KAI VANCE — AI Tech & Filmmaking
  youtube: {
    niches: ["All", "Neural CGI & VFX", "Cinema Camera Rigs", "Spatial Sound", "Creative Tech", "Color Science"],
    creators: [
      {
        id: 201,
        name: "Mateo Silva",
        handle: "@mateocode",
        avatar: "MS",
        avatarUrl: "/avatars/mateo.jpg",
        niche: "Creative Tech",
        platforms: ["youtube", "linkedin"],
        followers: "285K",
        engagement: "7.6%",
        matchScore: 99,
        style: "Fast-paced breakdown of open-source diffusion models, neural nerf capture & shaders",
        collab: "AI Agent vs Human Editor face-off, real-time virtual production demo",
        mutual: 8,
        verified: true,
        color: "from-emerald-400 via-teal-500 to-cyan-600",
      },
      {
        id: 202,
        name: "Elena Rostova",
        handle: "@elena.vfx",
        avatar: "ER",
        avatarUrl: "/avatars/elena.jpg",
        niche: "Neural CGI & VFX",
        platforms: ["youtube", "tiktok"],
        followers: "420K",
        engagement: "9.4%",
        matchScore: 98,
        style: "Unreal Engine 5.4 virtual sets, generative camera projection & gaussian splats",
        collab: "Full CGI short film built with 2 creators in 48 hours",
        mutual: 7,
        verified: true,
        color: "from-pink-500 via-purple-600 to-cyan-400",
      },
      {
        id: 203,
        name: "Kenji Takahashi",
        handle: "@kenji_beats",
        avatar: "KT",
        avatarUrl: "/avatars/kenji.jpg",
        niche: "Spatial Sound",
        platforms: ["youtube", "tiktok"],
        followers: "680K",
        engagement: "12.1%",
        matchScore: 96,
        style: "Dolby Atmos mixing, foley field recording & cinematic drone score composition",
        collab: "Custom soundtrack package for Kai's next 4K tech documentary",
        mutual: 6,
        verified: true,
        color: "from-cyan-400 via-blue-500 to-indigo-600",
      },
      {
        id: 204,
        name: "Amara Diop",
        handle: "@amarastories",
        avatar: "AD",
        avatarUrl: "/avatars/amara.jpg",
        niche: "Color Science",
        platforms: ["youtube", "instagram"],
        followers: "195K",
        engagement: "8.7%",
        matchScore: 94,
        style: "35mm anamorphic emulation, DaVinci Resolve color pipelines & narrative film craft",
        collab: "LUT pack launch & film stock blind test challenge",
        mutual: 5,
        verified: true,
        color: "from-amber-400 via-orange-500 to-rose-600",
      },
      {
        id: 205,
        name: "Liam O'Connor",
        handle: "@liamocreator",
        avatar: "LO",
        avatarUrl: "/avatars/liam.jpg",
        niche: "Creative Tech",
        platforms: ["youtube", "linkedin"],
        followers: "140K",
        engagement: "9.2%",
        matchScore: 91,
        style: "Studio gear architectures, multi-cam live-switching rigs & tech sponsorships",
        collab: "Ultimate $50,000 AI Production Studio build walkthrough",
        mutual: 4,
        verified: false,
        color: "from-indigo-500 via-purple-600 to-pink-500",
      },
      {
        id: 206,
        name: "Dr. Maya Lindqvist",
        handle: "@mayabrain.neuro",
        avatar: "ML",
        avatarUrl: "/avatars/maya.jpg",
        niche: "Creative Tech",
        platforms: ["youtube", "linkedin"],
        followers: "310K",
        engagement: "8.1%",
        matchScore: 89,
        style: "Viewer brain response to rapid visual cuts, retention neuropsychology",
        collab: "Eye-tracking heatmaps on Kai's viral YouTube intros",
        mutual: 3,
        verified: true,
        color: "from-teal-400 via-cyan-500 to-blue-600",
      },
      {
        id: 207,
        name: "Zara Chen",
        handle: "@zarastyle.lab",
        avatar: "ZC",
        avatarUrl: "/avatars/zara.jpg",
        niche: "Cinema Camera Rigs",
        platforms: ["youtube", "tiktok"],
        followers: "530K",
        engagement: "10.3%",
        matchScore: 88,
        style: "Modular camera harnesses, EDC tech gear sling design & carbon camera cages",
        collab: "Custom filmmaker EDC backpack & mobile rig breakdown",
        mutual: 3,
        verified: true,
        color: "from-rose-500 via-pink-600 to-purple-600",
      },
      {
        id: 208,
        name: "Felix Moreau",
        handle: "@felixcine.rigs",
        avatar: "FM",
        avatarUrl: "/avatars/liam.jpg",
        niche: "Cinema Camera Rigs",
        platforms: ["youtube"],
        followers: "420K",
        engagement: "8.3%",
        matchScore: 87,
        style: "RED V-Raptor vs ARRI Alexa Mini LF blind tests, anamorphic flare shootouts",
        collab: "Cinema Camera Blind Test with 10 industry DPs",
        mutual: 4,
        verified: true,
        color: "from-red-500 via-orange-500 to-amber-500",
      },
      {
        id: 209,
        name: "Arjun Mehta",
        handle: "@arjun_unreal",
        avatar: "AM",
        avatarUrl: "/avatars/kai.jpg",
        niche: "Neural CGI & VFX",
        platforms: ["youtube", "linkedin"],
        followers: "240K",
        engagement: "7.9%",
        matchScore: 85,
        style: "Realtime LED stage camera tracking, Blender geometry nodes & cinematic physics",
        collab: "Zero-budget virtual LED wall build tutorial",
        mutual: 3,
        verified: true,
        color: "from-blue-500 via-indigo-600 to-violet-500",
      },
      {
        id: 210,
        name: "Serafina Bloom",
        handle: "@serafinagrade",
        avatar: "SB",
        avatarUrl: "/avatars/aria.jpg",
        niche: "Color Science",
        platforms: ["youtube", "instagram"],
        followers: "180K",
        engagement: "9.5%",
        matchScore: 84,
        style: "ACES color management, film print density & split-toning magic",
        collab: "Grade my raw footage: Kai Vance cinematic footage test",
        mutual: 2,
        verified: false,
        color: "from-purple-500 via-pink-500 to-rose-500",
      },
      {
        id: 211,
        name: "Nikolai Voronin",
        handle: "@nikolai_drones",
        avatar: "NV",
        avatarUrl: "/avatars/marcus.jpg",
        niche: "Cinema Camera Rigs",
        platforms: ["youtube", "tiktok"],
        followers: "590K",
        engagement: "11.1%",
        matchScore: 82,
        style: "FPV cinematic dives through moving supercars, custom heavy-lifter cinema drones",
        collab: "Crazy one-take FPV chase sequence for Kai's next short",
        mutual: 3,
        verified: true,
        color: "from-cyan-500 via-blue-600 to-indigo-600",
      },
      {
        id: 212,
        name: "Yuki Tanaka",
        handle: "@yuki_audioengine",
        avatar: "YT",
        avatarUrl: "/avatars/kenji.jpg",
        niche: "Spatial Sound",
        platforms: ["youtube"],
        followers: "160K",
        engagement: "8.6%",
        matchScore: 80,
        style: "Binaural microphone placement, Foley sound recreation & reverb acoustic modeling",
        collab: "Microphone shootout: $200 vs $4,000 studio shotgun mics",
        mutual: 1,
        verified: false,
        color: "from-emerald-400 via-teal-500 to-cyan-500",
      },
      {
        id: 213,
        name: "Cassian Reed",
        handle: "@cassian_ai",
        avatar: "CR",
        avatarUrl: "/avatars/mateo.jpg",
        niche: "Creative Tech",
        platforms: ["youtube", "linkedin"],
        followers: "320K",
        engagement: "8.1%",
        matchScore: 79,
        style: "Text-to-video model evolution, Sora comparison benchmarks & prompt architecture",
        collab: "Can AI generate an entire Netflix trailer today? We tested it",
        mutual: 2,
        verified: true,
        color: "from-teal-400 via-blue-500 to-indigo-600",
      },
      {
        id: 214,
        name: "Astrid Lind",
        handle: "@astrid_filmtech",
        avatar: "AL",
        avatarUrl: "/avatars/maya.jpg",
        niche: "Neural CGI & VFX",
        platforms: ["youtube", "instagram"],
        followers: "210K",
        engagement: "7.8%",
        matchScore: 77,
        style: "Generative rotoscoping, automated depth map extraction & camera relighting",
        collab: "Replace my background with AI in 60 seconds (Photorealism test)",
        mutual: 1,
        verified: false,
        color: "from-pink-500 via-purple-600 to-blue-500",
      },
      {
        id: 215,
        name: "Hassan Qureshi",
        handle: "@hassan_lenslab",
        avatar: "HQ",
        avatarUrl: "/avatars/tariq.jpg",
        niche: "Cinema Camera Rigs",
        platforms: ["youtube"],
        followers: "145K",
        engagement: "8.4%",
        matchScore: 75,
        style: "Vintage Soviet anamorphic lens restoration, rehoused glass optical teardowns",
        collab: "Rehousing a $50 vintage lens to shoot like Hollywood",
        mutual: 0,
        verified: false,
        color: "from-amber-500 via-orange-600 to-red-500",
      },
    ],
  },

  // 3. NOVA STERLING — Viral Trends & Music Beats
  tiktok: {
    niches: ["All", "Audio Stem Drops", "Viral Pacing & Cuts", "Sub-Bass Loops", "Cyber Streetwear", "Pop Culture Remix"],
    creators: [
      {
        id: 301,
        name: "Kenji Takahashi",
        handle: "@kenji_beats",
        avatar: "KT",
        avatarUrl: "/avatars/kenji.jpg",
        niche: "Audio Stem Drops",
        platforms: ["tiktok", "youtube"],
        followers: "680K",
        engagement: "12.1%",
        matchScore: 99,
        style: "Analog modular synth drops, lo-fi beat flips & TikTok sound trending stems",
        collab: "Shared trending sound drop: 'Cyber Tokyo 2.0' (50K video sound target)",
        mutual: 9,
        verified: true,
        color: "from-cyan-400 via-blue-500 to-indigo-600",
      },
      {
        id: 302,
        name: "Zara Chen",
        handle: "@zarastyle.lab",
        avatar: "ZC",
        avatarUrl: "/avatars/zara.jpg",
        niche: "Cyber Streetwear",
        platforms: ["tiktok", "instagram"],
        followers: "530K",
        engagement: "10.3%",
        matchScore: 97,
        style: "Audio-synced fashion cuts, beat-drop clothing transitions & holographic fit checks",
        collab: "Beat-reactive LED streetwear sync reel, viral audio fit drop",
        mutual: 8,
        verified: true,
        color: "from-rose-500 via-pink-600 to-purple-600",
      },
      {
        id: 303,
        name: "Elena Rostova",
        handle: "@elena.vfx",
        avatar: "ER",
        avatarUrl: "/avatars/elena.jpg",
        niche: "Viral Pacing & Cuts",
        platforms: ["tiktok", "instagram"],
        followers: "420K",
        engagement: "9.4%",
        matchScore: 96,
        style: "Kinetic visualizer drops, 3D bass-reactive geometry loops & infinite zooms",
        collab: "Seamless audio-reactive 3D TikTok loop template",
        mutual: 7,
        verified: true,
        color: "from-pink-500 via-purple-600 to-cyan-400",
      },
      {
        id: 304,
        name: "Mateo Silva",
        handle: "@mateocode",
        avatar: "MS",
        avatarUrl: "/avatars/mateo.jpg",
        niche: "Sub-Bass Loops",
        platforms: ["tiktok", "youtube"],
        followers: "285K",
        engagement: "7.6%",
        matchScore: 93,
        style: "AI vocal stems, real-time audio visualizers coded in WebGL",
        collab: "Interactive mobile web soundboard for Nova's viral tracks",
        mutual: 6,
        verified: true,
        color: "from-emerald-400 via-teal-500 to-cyan-600",
      },
      {
        id: 305,
        name: "Amara Diop",
        handle: "@amarastories",
        avatar: "AD",
        avatarUrl: "/avatars/amara.jpg",
        niche: "Pop Culture Remix",
        platforms: ["tiktok", "instagram"],
        followers: "195K",
        engagement: "8.7%",
        matchScore: 91,
        style: "Rhythmic cultural documentary shorts, spoken word over hard electronic 808s",
        collab: "Spoken word poetry remix over Nova's signature synth pulse",
        mutual: 5,
        verified: true,
        color: "from-amber-400 via-orange-500 to-rose-600",
      },
      {
        id: 306,
        name: "Aria Thorne",
        handle: "@ariathorne.vibes",
        avatar: "AT",
        avatarUrl: "/avatars/aria.jpg",
        niche: "Cyber Streetwear",
        platforms: ["tiktok", "instagram"],
        followers: "148.5K",
        engagement: "8.6%",
        matchScore: 89,
        style: "High-intensity athletic speed edits synced to bass drops, futuristic athletic fits",
        collab: "Workout cadence sound challenge: Drop 20 reps on beat drop",
        mutual: 4,
        verified: true,
        color: "from-pink-500 via-rose-500 to-amber-500",
      },
      {
        id: 307,
        name: "Dr. Maya Lindqvist",
        handle: "@mayabrain.neuro",
        avatar: "ML",
        avatarUrl: "/avatars/maya.jpg",
        niche: "Viral Pacing & Cuts",
        platforms: ["tiktok", "youtube"],
        followers: "310K",
        engagement: "8.1%",
        matchScore: 87,
        style: "ASMR brain waves, binaural frequency effects & why certain sounds trigger chills",
        collab: "The Neuro-chemistry of Earworms: Why Nova's beats go viral",
        mutual: 3,
        verified: true,
        color: "from-teal-400 via-cyan-500 to-blue-600",
      },
      {
        id: 308,
        name: "Milo Vance",
        handle: "@milobeats.wav",
        avatar: "MV",
        avatarUrl: "/avatars/kai.jpg",
        niche: "Sub-Bass Loops",
        platforms: ["tiktok"],
        followers: "740K",
        engagement: "13.2%",
        matchScore: 86,
        style: "Drill 808 glides, sample flipping viral meme audios into club bangers",
        collab: "Beat switch challenge: 1 melody, 2 producers, 15 seconds",
        mutual: 5,
        verified: true,
        color: "from-violet-500 via-purple-600 to-pink-500",
      },
      {
        id: 309,
        name: "Kira Sato",
        handle: "@kiradances",
        avatar: "KS",
        avatarUrl: "/avatars/nova.jpg",
        niche: "Viral Pacing & Cuts",
        platforms: ["tiktok"],
        followers: "1.2M",
        engagement: "14.5%",
        matchScore: 84,
        style: "Sharp tutting, electronic popping, viral choreography designed for 9-second audios",
        collab: "Original dance trend choreography for Nova's next drop",
        mutual: 4,
        verified: true,
        color: "from-pink-500 via-purple-500 to-cyan-400",
      },
      {
        id: 310,
        name: "Brodie Sparks",
        handle: "@brodie_remix",
        avatar: "BS",
        avatarUrl: "/avatars/liam.jpg",
        niche: "Pop Culture Remix",
        platforms: ["tiktok", "youtube"],
        followers: "480K",
        engagement: "11.6%",
        matchScore: 83,
        style: "Turning kitchen sounds into bass house tracks, live micro-sampling",
        collab: "Sampling blender noises and turning it into a festival anthem",
        mutual: 3,
        verified: true,
        color: "from-yellow-400 via-amber-500 to-orange-500",
      },
      {
        id: 311,
        name: "Tariq Al-Mansoor",
        handle: "@tariqculinary",
        avatar: "TM",
        avatarUrl: "/avatars/tariq.jpg",
        niche: "Audio Stem Drops",
        platforms: ["tiktok", "instagram"],
        followers: "460K",
        engagement: "7.9%",
        matchScore: 81,
        style: "Hyper-crisp ASMR food sizzling, audio compression for viral food sounds",
        collab: "ASMR Sizzle & 808 beat drop: Kitchen culinary beat tape",
        mutual: 2,
        verified: false,
        color: "from-amber-500 via-orange-500 to-red-500",
      },
      {
        id: 312,
        name: "Jade Morrison",
        handle: "@jadelofi",
        avatar: "JM",
        avatarUrl: "/avatars/elena.jpg",
        niche: "Audio Stem Drops",
        platforms: ["tiktok", "youtube"],
        followers: "350K",
        engagement: "10.1%",
        matchScore: 80,
        style: "Melancholic piano chords, vinyl crackle textures & nostalgic anime pacing",
        collab: "Lo-Fi vs Cyberpunk beat clash: 1 vocal chop challenge",
        mutual: 2,
        verified: false,
        color: "from-indigo-400 via-purple-500 to-pink-500",
      },
      {
        id: 313,
        name: "Zephyr Quinn",
        handle: "@zephyredits",
        avatar: "ZQ",
        avatarUrl: "/avatars/mateo.jpg",
        niche: "Viral Pacing & Cuts",
        platforms: ["tiktok"],
        followers: "620K",
        engagement: "12.8%",
        matchScore: 78,
        style: "Velocity edit curves, speed ramping transitions & motion blur syncs",
        collab: "Velocity edit pack featuring Nova's unreleased stems",
        mutual: 1,
        verified: true,
        color: "from-cyan-400 via-teal-500 to-emerald-500",
      },
      {
        id: 314,
        name: "Leo Rossi",
        handle: "@leosynthwave",
        avatar: "LR",
        avatarUrl: "/avatars/marcus.jpg",
        niche: "Sub-Bass Loops",
        platforms: ["tiktok", "youtube"],
        followers: "290K",
        engagement: "9.3%",
        matchScore: 76,
        style: "1980s analog synthwave arpeggios, retrowave basslines & purple neon grids",
        collab: "Synthwave remix of Nova's viral TikTok hook",
        mutual: 1,
        verified: false,
        color: "from-purple-600 via-pink-600 to-cyan-500",
      },
      {
        id: 315,
        name: "Suki Hayashi",
        handle: "@sukigrooves",
        avatar: "SH",
        avatarUrl: "/avatars/amara.jpg",
        niche: "Pop Culture Remix",
        platforms: ["tiktok"],
        followers: "410K",
        engagement: "10.4%",
        matchScore: 74,
        style: "Japanese city pop samples modernized into UK garage and Jersey club bounces",
        collab: "Jersey club remix of Nova's trending audio track",
        mutual: 0,
        verified: false,
        color: "from-rose-400 via-pink-500 to-purple-600",
      },
    ],
  },

  // 4. MARCUS VANCE — Creator Economy & Growth
  linkedin: {
    niches: ["All", "Media Studio Systems", "Creator Revenue Teardowns", "B2B Brand Deals", "Neuro-Performance", "Algorithmic Growth"],
    creators: [
      {
        id: 401,
        name: "Liam O'Connor",
        handle: "@liamocreator",
        avatar: "LO",
        avatarUrl: "/avatars/liam.jpg",
        niche: "Media Studio Systems",
        platforms: ["linkedin", "youtube"],
        followers: "140K",
        engagement: "9.2%",
        matchScore: 98,
        style: "Pragmatic revenue teardowns, studio gear architectures & distribution graphs",
        collab: "The $1M Solo Operator Tech Stack: Co-written whitepaper & podcast",
        mutual: 9,
        verified: true,
        color: "from-indigo-500 via-purple-600 to-pink-500",
      },
      {
        id: 402,
        name: "Dr. Maya Lindqvist",
        handle: "@mayabrain.neuro",
        avatar: "ML",
        avatarUrl: "/avatars/maya.jpg",
        niche: "Neuro-Performance",
        platforms: ["linkedin", "youtube"],
        followers: "310K",
        engagement: "8.1%",
        matchScore: 96,
        style: "Deep-dive cognitive endurance breakdowns, founder burnout prevention & flow states",
        collab: "Mastering Executive Cognitive Endurance: Live webinar for top creators",
        mutual: 8,
        verified: true,
        color: "from-teal-400 via-cyan-500 to-blue-600",
      },
      {
        id: 403,
        name: "Mateo Silva",
        handle: "@mateocode",
        avatar: "MS",
        avatarUrl: "/avatars/mateo.jpg",
        niche: "Algorithmic Growth",
        platforms: ["linkedin", "youtube"],
        followers: "285K",
        engagement: "7.6%",
        matchScore: 94,
        style: "Autonomous agent workflows for media distribution, AI newsletter scraping engines",
        collab: "Building a 1-Person Autonomous Media Engine with Local LLMs",
        mutual: 7,
        verified: true,
        color: "from-emerald-400 via-teal-500 to-cyan-600",
      },
      {
        id: 404,
        name: "Amara Diop",
        handle: "@amarastories",
        avatar: "AD",
        avatarUrl: "/avatars/amara.jpg",
        niche: "B2B Brand Deals",
        platforms: ["linkedin", "instagram"],
        followers: "195K",
        engagement: "8.7%",
        matchScore: 92,
        style: "Brand storytelling frameworks, visual positioning for Fortune 500 sponsorships",
        collab: "Why Luxury Brands Pay 10x More to Narrative Creators (Case Teardown)",
        mutual: 6,
        verified: true,
        color: "from-amber-400 via-orange-500 to-rose-600",
      },
      {
        id: 405,
        name: "Zara Chen",
        handle: "@zarastyle.lab",
        avatar: "ZC",
        avatarUrl: "/avatars/zara.jpg",
        niche: "Creator Revenue Teardowns",
        platforms: ["linkedin", "tiktok"],
        followers: "530K",
        engagement: "10.3%",
        matchScore: 90,
        style: "DTC creator apparel margins, supply chain economics & capsule drop logistics",
        collab: "How Creators Are Generating 80% Gross Margins on Physical Merch",
        mutual: 5,
        verified: true,
        color: "from-rose-500 via-pink-600 to-purple-600",
      },
      {
        id: 406,
        name: "Elena Rostova",
        handle: "@elena.vfx",
        avatar: "ER",
        avatarUrl: "/avatars/elena.jpg",
        niche: "Media Studio Systems",
        platforms: ["linkedin", "tiktok"],
        followers: "420K",
        engagement: "9.4%",
        matchScore: 89,
        style: "Corporate CGI commercial pipelines, generative brand packaging",
        collab: "Enterprise VFX contracts for indie creators masterclass",
        mutual: 4,
        verified: true,
        color: "from-pink-500 via-purple-600 to-cyan-400",
      },
      {
        id: 407,
        name: "Kenji Takahashi",
        handle: "@kenji_beats",
        avatar: "KT",
        avatarUrl: "/avatars/kenji.jpg",
        niche: "Creator Revenue Teardowns",
        platforms: ["linkedin", "youtube"],
        followers: "680K",
        engagement: "12.1%",
        matchScore: 87,
        style: "Music licensing royalties, sync licensing for brands & catalog monetization",
        collab: "The Multi-Million Dollar Sync Licensing Blueprint for Creators",
        mutual: 4,
        verified: true,
        color: "from-cyan-400 via-blue-500 to-indigo-600",
      },
      {
        id: 408,
        name: "Tariq Al-Mansoor",
        handle: "@tariqculinary",
        avatar: "TM",
        avatarUrl: "/avatars/tariq.jpg",
        niche: "B2B Brand Deals",
        platforms: ["linkedin", "youtube"],
        followers: "460K",
        engagement: "7.9%",
        matchScore: 86,
        style: "Hospitality consulting, ghost kitchen franchising & packaged sauce scaling",
        collab: "From TikTok Chef to Multi-Unit Ghost Kitchen Franchise",
        mutual: 3,
        verified: false,
        color: "from-yellow-500 via-amber-500 to-red-500",
      },
      {
        id: 409,
        name: "Victoria Sterling",
        handle: "@vsterling_ventures",
        avatar: "VS",
        avatarUrl: "/avatars/aria.jpg",
        niche: "Creator Revenue Teardowns",
        platforms: ["linkedin"],
        followers: "185K",
        engagement: "10.6%",
        matchScore: 85,
        style: "Creator fund angel investing, cap tables & equity deals vs flat fee sponsorships",
        collab: "Stop Taking Cash: How Top 1% Creators Negotiate Equity in Brands",
        mutual: 5,
        verified: true,
        color: "from-blue-600 via-indigo-600 to-cyan-500",
      },
      {
        id: 410,
        name: "Devon Croft",
        handle: "@devon_retention",
        avatar: "DC",
        avatarUrl: "/avatars/kai.jpg",
        niche: "Algorithmic Growth",
        platforms: ["linkedin", "youtube"],
        followers: "260K",
        engagement: "8.9%",
        matchScore: 84,
        style: "Data-driven audience funnels, newsletter conversion math & churn optimization",
        collab: "Audience Monetization Teardown: Turning 100K Followers into $50K MRR",
        mutual: 4,
        verified: true,
        color: "from-teal-400 via-emerald-500 to-cyan-600",
      },
      {
        id: 411,
        name: "Alistair Thorne",
        handle: "@alistair_media",
        avatar: "AT",
        avatarUrl: "/avatars/marcus.jpg",
        niche: "Media Studio Systems",
        platforms: ["linkedin"],
        followers: "95K",
        engagement: "9.4%",
        matchScore: 82,
        style: "Hiring remote video editors, SOP systems for creator agencies & payroll scaling",
        collab: "The Zero-Headache Hiring SOP for Creator Teams",
        mutual: 3,
        verified: false,
        color: "from-purple-600 via-indigo-600 to-blue-500",
      },
      {
        id: 412,
        name: "Nora Varghese",
        handle: "@norasponsors",
        avatar: "NV",
        avatarUrl: "/avatars/nova.jpg",
        niche: "B2B Brand Deals",
        platforms: ["linkedin"],
        followers: "120K",
        engagement: "8.8%",
        matchScore: 81,
        style: "Enterprise B2B outreach templates, closing 6-figure SaaS sponsorships",
        collab: "Cold Email Templates that Closed $450K in B2B Creator Sponsorships",
        mutual: 2,
        verified: true,
        color: "from-pink-500 via-rose-500 to-purple-600",
      },
      {
        id: 413,
        name: "Julian Vance",
        handle: "@julian_scale",
        avatar: "JV",
        avatarUrl: "/avatars/liam.jpg",
        niche: "Algorithmic Growth",
        platforms: ["linkedin", "youtube"],
        followers: "310K",
        engagement: "7.7%",
        matchScore: 79,
        style: "YouTube longform SEO algorithms, title-thumbnail conversion testing frameworks",
        collab: "A/B Testing 1,000 Thumbnails: What Actually Drives CTR in 2026",
        mutual: 2,
        verified: false,
        color: "from-blue-500 via-cyan-500 to-teal-500",
      },
      {
        id: 414,
        name: "Dr. Ethan Cole",
        handle: "@drethancole",
        avatar: "EC",
        avatarUrl: "/avatars/maya.jpg",
        niche: "Neuro-Performance",
        platforms: ["linkedin"],
        followers: "140K",
        engagement: "8.3%",
        matchScore: 78,
        style: "CEO sleep architecture, circadian rhythm alignment for media leaders",
        collab: "The Executive Energy Protocol: Sleep & Cognitive Stack for Founders",
        mutual: 1,
        verified: false,
        color: "from-emerald-400 via-teal-500 to-blue-500",
      },
      {
        id: 415,
        name: "Clara Dubois",
        handle: "@clara_ip",
        avatar: "CD",
        avatarUrl: "/avatars/amara.jpg",
        niche: "Creator Revenue Teardowns",
        platforms: ["linkedin"],
        followers: "88K",
        engagement: "9.1%",
        matchScore: 75,
        style: "Trademark protection, creator IP licensing & contract loophole audits",
        collab: "Protect Your Brand: 5 Contract Clauses Every Creator Must Delete",
        mutual: 0,
        verified: true,
        color: "from-amber-500 via-orange-500 to-rose-500",
      },
    ],
  },
};
